name: Build and Deploy to Azure Container App

on:
  push:
    branches: [main]

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login bananagoldacr.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t bananagoldacr.azurecr.io/bananagold:latest -f ./dockerfile .

      - name: Push Docker image
        run: docker push bananagoldacr.azurecr.io/bananagold:latest

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: bananagoldacr
          containerAppName: bananagold
          resourceGroup: bananagold-rg
          containerAppEnvironment: bananagold-env
          imageToDeploy: bananagoldacr.azurecr.io/bananagold:latest
          targetPort: 443
