name: Build and Deploy to Azure Container App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push container image to ACR
      uses: azure/container-apps-deploy-action@v1
      with:
        registry-url: bananagoldacr.azurecr.io
        container-app-name: bananagold
        resource-group: bananagold-rg
        image: bananagoldacr.azurecr.io/bananagold:githublatest
        dockerfile: ./Dockerfile
        targetPort: 443
        environment: bananagold-env
