name: Build and Deploy to Azure Container App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to ACR
      run: az acr login --name bananagoldacr

    - name: Build Docker image
      run: docker build -t bananagoldacr.azurecr.io/bananagold:latest .

    - name: Push Docker image to ACR
      run: docker push bananagoldacr.azurecr.io/bananagold:latest

    - name: Deploy image to Azure Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        imageToDeploy: bananagoldacr.azurecr.io/bananagold:latest
        containerAppName: bananagold
        resourceGroup: bananagold-rg
        containerAppEnvironment: bananagold-env
        targetPort: 80
