name: Build and Deploy to Azure Container App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: bananagoldacr
        containerAppName: bananagold
        resourceGroup: bananagold-rg
        containerAppEnvironment: bananagold-env
        imageToBuild: bananagoldacr.azurecr.io/bananagold:githublatest
        dockerfilePath: ./Dockerfile
        targetPort: 443
